// <auto-generated />
namespace TitleTurtle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Init7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init7));
        
        string IMigrationMetadata.Id
        {
            get { return "201408022000134_Init7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
